### ISSUE TITLE
Preview: background color partially dark under dark theme

### ISSUE THREAD

**Issue by fap-** [skuro/plantuml-mode#52] opened 2017-02-07 14:59 UTC
I'm not sure if this is something plantuml-mode can fix.

plantuml-mode version: 20161111.205
PlantUML Version 8049
GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2016-12-21

![emacs25 angelus_019](https://cloud.githubusercontent.com/assets/459631/22696287/c0922848-ed4d-11e6-8890-d5985e06de53.png)

**Comment by skuro** [comment] 2017-02-07 16:41
Mhhhhhh I have a dark theme myself and I cannot see the issue. Could you please share a `.puml` file that can reproduce the issue? Also, what emacs color scheme are you using?

**Comment by fap-** [comment] 2017-02-08 23:06
I'm using https://github.com/oneKelvinSmith/monokai-emacs.
I don't get this error on my tower, which is running Linux Mint + Cinnamon. Only on my notebook with Ubuntu + Unity.

**Comment by skuro** [comment] 2017-05-10 21:17
Sorry for the heavy delay, got carried away by life I guess..  Anyway, do you still have the same issue? I forgot to ask, what output format are you using, PNG or SVG?

**Comment by skuro** [comment] 2017-07-07 17:04
I couldn't reproduce the issue. I'll close this one for now, @fap- feel free to reopen if you have any more detail to share.

**Closed by skuro** 2017-07-07 17:04 UTC
