### ISSUE TITLE
The preview error on Unicode character

### ISSUE THREAD

**Issue by pengux** [skuro/plantuml-mode#50] opened 2016-11-29 18:19 UTC
# Summary
When using plantuml preview, the SVG file contains syntax error because of Unicode characters. This does not happen when using command line to run the plantuml.jar file.

**Comment by skuro** [comment] 2016-12-25 17:41
Could you please give some more context here? Useful info include the error message, and the content of the `*PLANTUML Messages*` buffer. Please remember to `plantuml-enable-debug` before trying to preview. Also, can you please provide a sample `.plantuml` file with unicode content I can use for debugging?

**Comment by skuro** [comment] 2016-12-25 18:18
Just added a [commit](06a12c3d1655219deccc0432ff671339d48c776c) with a failing test that can reproduce your issue. I'm still uncertain about where the issue stems from, since it seems to me that all encodings are properly set. More investigations are needed.

**Comment by skuro** [comment] 2016-12-25 19:43
Should be fixed in latest `master`, or in `v1.2.3` (just released, might take a while before it pops up in MELPA)

**Closed by skuro** 2016-12-25 19:44 UTC
Labels: bug, help-wanted
